#!/usr/bin/env python3
"""
Interactive knowledge graph viewer using Dash Cytoscape.

Usage:
  python kg_dash_viewer.py --graph ./google100_graph.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import defaultdict, deque
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Set, Tuple

from dash import Dash, Input, Output, dcc, html
import dash_cytoscape as cyto


PALETTE = [
    "#1f77b4",
    "#ff7f0e",
    "#2ca02c",
    "#d62728",
    "#9467bd",
    "#8c564b",
    "#e377c2",
    "#7f7f7f",
    "#bcbd22",
    "#17becf",
    "#4c78a8",
    "#f58518",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Interactive viewer for KG graph JSON.")
    parser.add_argument(
        "--graph",
        default="google100_graph.json",
        help="Graph JSON file generated by kg_pipeline.py.",
    )
    parser.add_argument("--host", default="127.0.0.1", help="Dash host.")
    parser.add_argument("--port", type=int, default=8050, help="Dash port.")
    parser.add_argument("--debug", action="store_true", help="Enable Dash debug mode.")
    return parser.parse_args()


def load_graph(path: Path) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Graph JSON must be a dict payload.")
    nodes = payload.get("nodes", [])
    edges = payload.get("edges", [])
    if not isinstance(nodes, list) or not isinstance(edges, list):
        raise ValueError("Graph JSON must contain list fields 'nodes' and 'edges'.")
    safe_nodes = [n for n in nodes if isinstance(n, dict)]
    safe_edges = [e for e in edges if isinstance(e, dict)]
    return safe_nodes, safe_edges


def canonical_node_name(node: Dict[str, Any]) -> str:
    name = str(node.get("canonical_name") or "").strip()
    return name or str(node.get("node_id") or "unknown-node")


def canonical_edge_name(edge: Dict[str, Any]) -> str:
    name = str(edge.get("canonical_name") or "").strip()
    if name:
        return name
    rel_type = str(edge.get("rel_type") or "").strip()
    return rel_type or "related_to"


def node_type_value(node: Dict[str, Any]) -> str:
    value = str(node.get("type") or "").strip()
    return value if value else "(unknown)"


def rel_type_value(edge: Dict[str, Any]) -> str:
    value = str(edge.get("rel_type") or "").strip()
    return value if value else "(unknown)"


def stable_color(label: str) -> str:
    key = (label or "").strip().lower()
    if not key:
        return "#9ca3af"
    digest = hashlib.md5(key.encode("utf-8")).hexdigest()
    idx = int(digest[:8], 16) % len(PALETTE)
    return PALETTE[idx]


def unique_sorted(values: Iterable[str]) -> List[str]:
    return sorted({str(v).strip() for v in values if str(v).strip()})


def build_adjacency(edges: Sequence[Dict[str, Any]]) -> Dict[str, Set[str]]:
    graph: Dict[str, Set[str]] = defaultdict(set)
    for edge in edges:
        src = str(edge.get("src_id") or "").strip()
        dst = str(edge.get("dst_id") or "").strip()
        if not src or not dst:
            continue
        graph[src].add(dst)
        graph[dst].add(src)
    return graph


def compute_degrees(edges: Sequence[Dict[str, Any]]) -> Dict[str, int]:
    degree: Dict[str, int] = defaultdict(int)
    for edge in edges:
        src = str(edge.get("src_id") or "").strip()
        dst = str(edge.get("dst_id") or "").strip()
        if src:
            degree[src] += 1
        if dst:
            degree[dst] += 1
    return degree


def bfs_neighborhood(adjacency: Dict[str, Set[str]], root: str, depth: int) -> Set[str]:
    if not root or depth < 0:
        return set()
    visited: Set[str] = {root}
    queue: deque[Tuple[str, int]] = deque([(root, 0)])
    while queue:
        node_id, dist = queue.popleft()
        if dist >= depth:
            continue
        for nxt in adjacency.get(node_id, set()):
            if nxt in visited:
                continue
            visited.add(nxt)
            queue.append((nxt, dist + 1))
    return visited


def make_stylesheet(show_edge_labels: bool, max_degree: int) -> List[Dict[str, Any]]:
    max_degree = max(max_degree, 1)
    base = [
        {
            "selector": "node",
            "style": {
                "label": "data(label)",
                "font-size": 10,
                "text-wrap": "wrap",
                "text-max-width": 140,
                "background-color": "data(color)",
                "color": "#111827",
                "border-width": 1.2,
                "border-color": "#1f2937",
                "width": f"mapData(degree, 0, {max_degree}, 14, 54)",
                "height": f"mapData(degree, 0, {max_degree}, 14, 54)",
            },
        },
        {
            "selector": "edge",
            "style": {
                "curve-style": "bezier",
                "line-color": "#9ca3af",
                "target-arrow-color": "#9ca3af",
                "target-arrow-shape": "triangle",
                "arrow-scale": 0.8,
                "width": 1.4,
            },
        },
    ]
    if show_edge_labels:
        base.append(
            {
                "selector": "edge",
                "style": {
                    "label": "data(label)",
                    "font-size": 8,
                    "text-wrap": "wrap",
                    "text-max-width": 130,
                    "text-background-opacity": 0.8,
                    "text-background-color": "#ffffff",
                    "text-background-padding": 2,
                },
            }
        )
    return base


def main() -> None:
    args = parse_args()
    graph_path = Path(args.graph)
    if not graph_path.exists():
        raise FileNotFoundError(f"Graph path not found: {graph_path}")

    nodes, edges = load_graph(graph_path)
    node_by_id: Dict[str, Dict[str, Any]] = {
        str(node.get("node_id")): node for node in nodes if str(node.get("node_id") or "").strip()
    }
    edges = [
        edge
        for edge in edges
        if str(edge.get("src_id") or "").strip() in node_by_id and str(edge.get("dst_id") or "").strip() in node_by_id
    ]

    adjacency = build_adjacency(edges)
    degree_by_node = compute_degrees(edges)
    max_degree = max([0, *degree_by_node.values()])

    type_values = unique_sorted(node_type_value(node) for node in node_by_id.values())
    rel_values = unique_sorted(rel_type_value(edge) for edge in edges)
    node_options = [
        {
            "label": f"{canonical_node_name(node)} ({node_id})",
            "value": node_id,
        }
        for node_id, node in sorted(
            node_by_id.items(),
            key=lambda item: canonical_node_name(item[1]).lower(),
        )
    ]

    limit_min = 10 if len(node_by_id) >= 10 else 1
    limit_max = max(limit_min, len(node_by_id))
    limit_default = min(250, len(node_by_id)) if node_by_id else limit_min
    limit_default = max(limit_min, min(limit_default, limit_max))

    limit_step = 10 if (limit_max - limit_min) >= 10 else 1

    app = Dash(__name__)
    app.title = "KG Explorer"

    app.layout = html.Div(
        [
            html.H2("Knowledge Graph Explorer"),
            html.Div(
                [
                    html.Div(
                        [
                            html.Div("Search (name, alt name, attributes)", style={"fontWeight": "600"}),
                            dcc.Input(
                                id="search-text",
                                type="text",
                                placeholder="e.g. Google, Gemini, antitrust ...",
                                debounce=True,
                                style={"width": "100%"},
                            ),
                            html.Div("Node types", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Dropdown(
                                id="node-types",
                                options=[{"label": x, "value": x} for x in type_values],
                                multi=True,
                                value=[],
                                placeholder="Filter node types...",
                            ),
                            html.Div("Relation types", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Dropdown(
                                id="relation-types",
                                options=[{"label": x, "value": x} for x in rel_values],
                                multi=True,
                                value=[],
                                placeholder="Filter relation types...",
                            ),
                            html.Div("Minimum degree", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Slider(
                                id="min-degree",
                                min=0,
                                max=max_degree if max_degree > 0 else 1,
                                step=1,
                                value=0,
                                marks={0: "0", max_degree: str(max_degree)} if max_degree > 0 else {0: "0", 1: "1"},
                            ),
                            html.Div("Node limit", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Slider(
                                id="node-limit",
                                min=limit_min,
                                max=limit_max,
                                step=limit_step,
                                value=limit_default,
                                marks={limit_min: str(limit_min), limit_max: str(limit_max)},
                            ),
                            html.Div("Ego node", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Dropdown(
                                id="ego-node",
                                options=node_options,
                                value=None,
                                placeholder="Optional focus node...",
                            ),
                            html.Div("Ego depth", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Slider(
                                id="ego-depth",
                                min=0,
                                max=3,
                                step=1,
                                value=1,
                                marks={0: "0", 1: "1", 2: "2", 3: "3"},
                            ),
                            html.Div("Layout", style={"fontWeight": "600", "marginTop": "12px"}),
                            dcc.Dropdown(
                                id="layout-name",
                                options=[
                                    {"label": "COSE (force-directed)", "value": "cose"},
                                    {"label": "Concentric", "value": "concentric"},
                                    {"label": "Breadthfirst", "value": "breadthfirst"},
                                    {"label": "Circle", "value": "circle"},
                                    {"label": "Grid", "value": "grid"},
                                ],
                                value="cose",
                                clearable=False,
                            ),
                            dcc.Checklist(
                                id="edge-label-toggle",
                                options=[{"label": "Show edge labels", "value": "show"}],
                                value=[],
                                style={"marginTop": "10px"},
                            ),
                        ],
                        style={
                            "flex": "0 0 330px",
                            "padding": "12px",
                            "border": "1px solid #d1d5db",
                            "borderRadius": "8px",
                            "backgroundColor": "#f9fafb",
                            "height": "86vh",
                            "overflowY": "auto",
                        },
                    ),
                    html.Div(
                        [
                            html.Div(id="stats-line", style={"marginBottom": "8px", "fontWeight": "600"}),
                            html.Div(id="filter-warning", style={"marginBottom": "8px", "color": "#b45309"}),
                            cyto.Cytoscape(
                                id="kg-cytoscape",
                                elements=[],
                                stylesheet=make_stylesheet(show_edge_labels=False, max_degree=max_degree),
                                style={
                                    "width": "100%",
                                    "height": "78vh",
                                    "border": "1px solid #d1d5db",
                                    "borderRadius": "8px",
                                    "backgroundColor": "#ffffff",
                                },
                                layout={"name": "cose", "animate": False},
                            ),
                        ],
                        style={"flex": "1 1 auto", "padding": "0 12px"},
                    ),
                    html.Div(
                        [
                            html.H4("Selection"),
                            html.Div(
                                "Click a node or edge to inspect details.",
                                style={"color": "#6b7280", "marginBottom": "8px"},
                            ),
                            html.Pre(
                                id="selection-panel",
                                style={
                                    "whiteSpace": "pre-wrap",
                                    "fontSize": "12px",
                                    "lineHeight": "1.35",
                                    "backgroundColor": "#f9fafb",
                                    "border": "1px solid #d1d5db",
                                    "borderRadius": "6px",
                                    "padding": "10px",
                                },
                            ),
                        ],
                        style={
                            "flex": "0 0 330px",
                            "padding": "12px",
                            "border": "1px solid #d1d5db",
                            "borderRadius": "8px",
                            "backgroundColor": "#ffffff",
                            "height": "86vh",
                            "overflowY": "auto",
                        },
                    ),
                ],
                style={"display": "flex", "gap": "10px"},
            ),
        ],
        style={"fontFamily": "Arial, sans-serif", "padding": "12px"},
    )

    @app.callback(
        Output("kg-cytoscape", "elements"),
        Output("kg-cytoscape", "layout"),
        Output("kg-cytoscape", "stylesheet"),
        Output("stats-line", "children"),
        Output("filter-warning", "children"),
        Input("search-text", "value"),
        Input("node-types", "value"),
        Input("relation-types", "value"),
        Input("min-degree", "value"),
        Input("node-limit", "value"),
        Input("ego-node", "value"),
        Input("ego-depth", "value"),
        Input("layout-name", "value"),
        Input("edge-label-toggle", "value"),
    )
    def update_graph(
        search_text: str,
        selected_node_types: List[str],
        selected_rel_types: List[str],
        min_degree: int,
        node_limit: int,
        ego_node: str,
        ego_depth: int,
        layout_name: str,
        edge_label_toggle: List[str],
    ) -> Tuple[List[Dict[str, Any]], Dict[str, Any], List[Dict[str, Any]], str, str]:
        selected_node_types = selected_node_types or []
        selected_rel_types = selected_rel_types or []
        min_degree = max(0, int(min_degree or 0))
        node_limit = max(1, int(node_limit or len(node_by_id)))
        ego_depth = max(0, int(ego_depth or 0))
        query = (search_text or "").strip().lower()
        show_edge_labels = "show" in (edge_label_toggle or [])

        candidate_nodes: Set[str] = set(node_by_id.keys())
        if selected_node_types:
            allowed_types = set(selected_node_types)
            candidate_nodes &= {
                node_id for node_id, node in node_by_id.items() if node_type_value(node) in allowed_types
            }

        if min_degree > 0:
            candidate_nodes &= {
                node_id for node_id in candidate_nodes if degree_by_node.get(node_id, 0) >= min_degree
            }

        if query:
            matched: Set[str] = set()
            for node_id in candidate_nodes:
                node = node_by_id[node_id]
                haystack_parts = [
                    canonical_node_name(node),
                    *[str(x) for x in node.get("alt_names", []) if isinstance(x, str)],
                    *[str(x) for x in node.get("attributes", []) if isinstance(x, str)],
                    str(node.get("type") or ""),
                ]
                haystack = " | ".join(haystack_parts).lower()
                if query in haystack:
                    matched.add(node_id)
            candidate_nodes = matched

        if ego_node:
            ego_set = bfs_neighborhood(adjacency, ego_node, ego_depth)
            candidate_nodes &= ego_set

        ranked_nodes = sorted(
            candidate_nodes,
            key=lambda node_id: (
                degree_by_node.get(node_id, 0),
                canonical_node_name(node_by_id[node_id]).lower(),
            ),
            reverse=True,
        )
        limited_nodes = set(ranked_nodes[:node_limit])

        filtered_edges: List[Dict[str, Any]] = []
        allowed_rel_types = set(selected_rel_types)
        for edge in edges:
            src = str(edge.get("src_id") or "").strip()
            dst = str(edge.get("dst_id") or "").strip()
            if src not in limited_nodes or dst not in limited_nodes:
                continue
            if allowed_rel_types and rel_type_value(edge) not in allowed_rel_types:
                continue
            filtered_edges.append(edge)

        connected_nodes = {str(e.get("src_id")) for e in filtered_edges} | {str(e.get("dst_id")) for e in filtered_edges}
        final_node_ids = set(limited_nodes) | connected_nodes

        node_elements: List[Dict[str, Any]] = []
        for node_id in sorted(final_node_ids, key=lambda x: canonical_node_name(node_by_id[x]).lower()):
            node = node_by_id[node_id]
            node_elements.append(
                {
                    "data": {
                        "id": node_id,
                        "label": canonical_node_name(node),
                        "type": node_type_value(node),
                        "degree": degree_by_node.get(node_id, 0),
                        "color": stable_color(node_type_value(node)),
                    }
                }
            )

        edge_elements = [
            {
                "data": {
                    "id": str(edge.get("edge_id") or f"{edge.get('src_id')}->{edge.get('dst_id')}"),
                    "source": str(edge.get("src_id")),
                    "target": str(edge.get("dst_id")),
                    "label": canonical_edge_name(edge),
                    "rel_type": rel_type_value(edge),
                }
            }
            for edge in filtered_edges
        ]

        elements = [*node_elements, *edge_elements]
        layout = {"name": layout_name or "cose", "animate": False}
        if (layout_name or "") == "breadthfirst" and ego_node and ego_node in final_node_ids:
            layout["roots"] = f"#{ego_node}"
        stylesheet = make_stylesheet(show_edge_labels=show_edge_labels, max_degree=max_degree)

        stats = (
            f"Showing {len(node_elements)} nodes / {len(edge_elements)} edges "
            f"(from {len(node_by_id)} nodes / {len(edges)} edges total)"
        )
        warning = ""
        if not node_elements:
            warning = "No nodes match current filters."
        elif len(candidate_nodes) > node_limit:
            warning = f"Filtered node set truncated by node limit: {node_limit}."

        return elements, layout, stylesheet, stats, warning

    @app.callback(
        Output("selection-panel", "children"),
        Input("kg-cytoscape", "tapNodeData"),
        Input("kg-cytoscape", "tapEdgeData"),
    )
    def render_selection(node_data: Dict[str, Any], edge_data: Dict[str, Any]) -> str:
        if node_data:
            node_id = str(node_data.get("id") or "")
            node = node_by_id.get(node_id, {})
            payload = {
                "kind": "node",
                "node_id": node_id,
                "canonical_name": canonical_node_name(node),
                "type": node_type_value(node),
                "degree": degree_by_node.get(node_id, 0),
                "alt_names": node.get("alt_names", []),
                "attributes": node.get("attributes", []),
                "created_at": node.get("created_at"),
                "updated_at": node.get("updated_at"),
            }
            return json.dumps(payload, ensure_ascii=False, indent=2)

        if edge_data:
            payload = {
                "kind": "edge",
                "edge_id": edge_data.get("id"),
                "source": edge_data.get("source"),
                "target": edge_data.get("target"),
                "canonical_name": edge_data.get("label"),
                "rel_type": edge_data.get("rel_type"),
            }
            return json.dumps(payload, ensure_ascii=False, indent=2)

        return ""

    app.run(host=args.host, port=args.port, debug=args.debug)


if __name__ == "__main__":
    main()
